% Visualise the radio-frequency (RF) element echo data generated by
% RF_simulator4.1
%
% Nathan Blanken, University of Twente, 2021

clear
clc

% File location
delim       = '\'; 
foldername  = 'D:\BubbleSimulations\Results15';
filename    = 'BubblesOnly00002.mat';
filedir     = [foldername delim filename];

signal_type = 'pressure';   
t_start     = 5;    % microseconds
t_end       = 20;   % microseconds

load(filedir)

N = length(RF(1).p);        % number of samples per RF line
Nelem = length(RF);         % number of transducer elements

Fs = RF(1).fs;              % sample rate (Hz)
t = (0:(N-1))/Fs;           % time axis (s)

% Convert struct to matrix
switch signal_type
    case 'pressure'
        RF_matrix = [RF.p];
    case 'voltage'
        RF_matrix = [RF.V];
end

RF_matrix = reshape(RF_matrix, N, Nelem)';  % matrix of element RF data


% Show the data
imagesc(t*1e6, 1:Nelem, RF_matrix)
xlim([t_start t_end])
cb = colorbar;
xlabel(' t(\mus)')
ylabel('element number')

if strcmp(signal_type,'pressure')
    cb.Title.String = 'p (kPa)';
end